# Generated by Django 4.2 on 2023-08-29 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_brand_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='Image',
            new_name='image',
        ),
    ]
