# Generated by Django 4.2 on 2023-11-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_rename_phone_company_address_company_phones'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.FloatField()),
            ],
        ),
    ]
