# Generated by Django 4.2 on 2023-09-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_image_brand_image'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart_Detail',
            new_name='CartDetail',
        ),
        migrations.RenameModel(
            old_name='Order_Detail',
            new_name='OrderDetail',
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='uta6dya4', max_length=100),
        ),
    ]
