# Generated by Django 4.2 on 2023-09-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_code_alter_order_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('InProgress', 'InProgress'), ('Completed', 'Completed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='1uf31okf', max_length=100),
        ),
    ]
